// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaWuA1Ie0XjlKfGInpumrL5S-efSIWoEY',
    appId: '1:893776644724:web:b52a510a15d5f9a85bdf21',
    messagingSenderId: '893776644724',
    projectId: 'dicoding-chatting-16fd4',
    authDomain: 'dicoding-chatting-16fd4.firebaseapp.com',
    storageBucket: 'dicoding-chatting-16fd4.appspot.com',
    measurementId: 'G-78R0HWCBD4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4QXzHR_AtOQdLpVzYpMmbM9O6ZXJMBqo',
    appId: '1:893776644724:android:329c661f6586139a5bdf21',
    messagingSenderId: '893776644724',
    projectId: 'dicoding-chatting-16fd4',
    storageBucket: 'dicoding-chatting-16fd4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbpW-b-UKUwihTWf9M20Vk3LA1BlWoyao',
    appId: '1:893776644724:ios:ae9b6fe3622c20fa5bdf21',
    messagingSenderId: '893776644724',
    projectId: 'dicoding-chatting-16fd4',
    storageBucket: 'dicoding-chatting-16fd4.appspot.com',
    iosBundleId: 'com.example.dicodingChatting',
  );
}
